version: '3'
services:
  app:
      image: msitdevops/myapp:1.0.0
      ports:
        - "8089:8089"
      depends_on:
        - mysql
  mysql:
      image: mysql:latest
      
      environment:
        - MYSQL_DATABASE: "springbootrocks"
        - MYSQL_USER: "root"
        - MYSQL_PASSWORD: "admin"
        - MYSQL_ROOT_PASSWORD: "admin"
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - "3309:3306"
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      container_name: mysql
