version: '3.0'
services:

  web:
      image: nginx
      deploy:
        replicas: 5
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
        restart_policy:
          condition: on-failure
      ports:
        - "8089:8080"
  databse:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'springbootrocks'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'admin'
        MYSQL_ROOT_PASSWORD: 'admin'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      volumes:
        - my-db:/var/lib/mysql
